spring.application.name=fiberTower


# Database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/circuits?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=*M@815&699s$
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA configuration (optional, if using JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT configuration
jwt.secret=MySecureJWTSecretKeyForAccessParksCircuitsApp2024x8F9d2K4mL7pQ3rT5uV6wX9yZ1aBcDeFgHiJkLmNoPqRs
jwt.expiration=86400000